# -*- coding: utf-8 -*-
"""EDA ֹ_final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1198_qAzuXm5htjFWfzumhg9ibFZgRadc

Introduction and dataset description
"""

import matplotlib.pyplot as plt
import seaborn as sns

#1. Data Cleaning & Exploration
from google.colab import files
files.upload()
import pandas as pd
df_taylor=pd.read_csv('taylor_swift_spotify.csv')
df_taylor.head()

df_taylor.shape

df_taylor.describe()

df_taylor.info()

df_taylor.isnull().sum()

df_taylor.duplicated().sum()

"""Data cleaning and preprocessing"""

#df_taylor.columns

#3.logical grouping (album families)
df_taylor['album'].unique()
df_taylor['album'].value_counts()

eras=['THE TORTURED POETS DEPARTMENT','Midnights','evermore','folklore','Lover','reputation','1989','Red','Speak Now','Fearless','Live From Clear Channel','Taylor Swift (Deluxe Edition)']

#copy album colunm and naming it album_families
df_taylor['album_families']=df_taylor['album']
#df_taylor.head()

#df_taylor.isnull().sum()

def map_album(album_title):
  for album_t in eras:
    if album_t in album_title:
      return album_t
  return album_title

df_taylor['album_families']=df_taylor['album'].apply(map_album)

#df_taylor['album_families'].unique()

df_taylor['album_families'].value_counts()

#df_taylor.describe()

#df_taylor.isnull().sum()

#df_taylor['album_families']

df_taylor['release_date'].unique()

df_taylor['release_year'] = df_taylor['release_date'].str[:4].astype(int)
#df_taylor['release_year']

"""Univariate analysis - popularity"""

df_taylor['popularity'].describe()

popularity=df_taylor['popularity']
mode_popularity=df_taylor['popularity'].mode()[0]  #left skewed
mean_popularity=df_taylor['popularity'].mean()
median_popularity=df_taylor['popularity'].median()
print(f"The mode popularity is: {mode_popularity}")

#plt.figure(figsize=(10, 5))

#sns.histplot(popularity, bins=40)

#plt.axvline(mean_popularity, color="red", linestyle="--", linewidth=2, label="Mean")
#plt.axvline(median_popularity, color="green", linestyle="-", linewidth=2, label="Median")
#plt.axvline(mode_popularity, color="blue", linestyle=":", linewidth=2, label="Mode")

#plt.title("Center of popularity data")
#plt.xlabel("Popularity")
#plt.ylabel("frequency")
#plt.legend()
#plt.savefig('Center of popularity data')

#plt.show()

#plt.figure(figsize=(5, 6))
#sns.boxplot(x='popularity', data=df_taylor, color='lightblue', width=0.4)

#plt.title("Boxplot of Song Popularity (Outlier Detection)", fontsize=12, fontweight='bold', pad=15)
#plt.xlabel("Popularity Score (0 - 100)", fontsize=11)
#plt.grid(axis='x', linestyle=':', alpha=0.6)
#plt.show()

q1_popularity=df_taylor['popularity'].quantile(0.25)
q3_popularity=df_taylor['popularity'].quantile(0.75)
iqr_popularuty= q3_popularity - q1_popularity

lower_fence_popularity=q1_popularity - 1.5 * iqr_popularuty
upper_fence_popularity=q3_popularity + 1.5 * iqr_popularuty

print(f"The lower fence of popularity is: {lower_fence_popularity}")
print(f"The upper fence of popularity is: {upper_fence_popularity}")

outliers_popularity=df_taylor[(df_taylor['popularity']<lower_fence_popularity)|(df_taylor['popularity']>upper_fence_popularity)]
df_outliers_popularity=pd.DataFrame(outliers_popularity)
df_outliers_popularity['popularity']

df_outliers_popularity

print("Skewness of 'popularity':", df_taylor['popularity'].skew())

import matplotlib.pyplot as plt
import seaborn as sns

# Set optimal compact dimensions for clear readability in ACL format
plt.figure(figsize=(9, 4))

# --- Plot 1: Histogram (Left) ---
plt.subplot(1, 2, 1)
sns.histplot(popularity, bins=40)

# Using your exact predefined central tendency variables
plt.axvline(mean_popularity, color="red", linestyle="--", linewidth=1.5, label="Mean")
plt.axvline(median_popularity, color="green", linestyle="-", linewidth=1.5, label="Median")
plt.axvline(mode_popularity, color="blue", linestyle=":", linewidth=1.5, label="Mode")

#plt.title("Center of popularity data", fontsize=10, fontweight='bold')
plt.xlabel("Popularity", fontsize=9)
plt.ylabel("frequency", fontsize=9)
plt.xticks(fontsize=9)
plt.yticks(fontsize=9)
plt.legend(fontsize=8, loc='upper left')

# --- Plot 2: Boxplot (Right) ---
plt.subplot(1, 2, 2)
sns.boxplot(x='popularity', data=df_taylor, color='lightblue', width=0.4)

#plt.title("Boxplot of Song Popularity (Outlier Detection)", fontsize=10, fontweight='bold')
plt.xlabel("Popularity Score (0 - 100)", fontsize=9)
plt.xticks(fontsize=9)
plt.grid(axis='x', linestyle=':', alpha=0.5)

# Adjust padding at the bottom to guarantee labels are fully visible and readable
plt.subplots_adjust(bottom=0.2)

plt.tight_layout()
plt.savefig('Figure_1_Popularity_Univariate', dpi=300, bbox_inches='tight')
plt.show()

"""Univariate analysis - danceability



"""

df_taylor['danceability'].describe()

mean_dance=df_taylor['danceability'].mean()
median_dance=df_taylor['danceability'].median()
mode_dance=df_taylor['danceability'].mode()[0]
print(f"The mode danceability is:{mode_dance}")

print("Skewness of 'danceability':" ,df_taylor['danceability'].skew())

#plt.figure(figsize=(9, 5))
#sns.histplot(df_taylor['danceability'], kde=True, color='purple', bins=20)

#plt.axvline(mean_dance, color="red", linestyle="--", linewidth=2, label="Mean")
#plt.axvline(median_dance, color="green", linestyle="-", linewidth=2, label="Median")
#plt.axvline(mode_dance, color="blue", linestyle=":", linewidth=2, label="Mode")

#plt.title("Center of danceability data")


#plt.title("Distribution of danceability", fontsize=14, fontweight='bold', pad=12)
#plt.xlabel("danceability", fontsize=11)
#plt.ylabel("frequency", fontsize=11)
#plt.grid(axis='y', linestyle=':', alpha=0.6)
#plt.show()

#plt.figure(figsize=(5, 6))
#sns.boxplot(x='danceability', data=df_taylor, color='lightblue', width=0.4)

#plt.title("Boxplot of Song danceability (Outlier Detection)", fontsize=12, fontweight='bold', pad=15)
#plt.xlabel("danceability", fontsize=11)
#plt.grid(axis='x', linestyle=':', alpha=0.6)
#plt.show()

# detact danceability outliers values

q1_dance=df_taylor['danceability'].quantile(0.25)
q3_dance=df_taylor['danceability'].quantile(0.75)
iqr_dance= q3_dance - q1_dance

lower_fence_dance=q1_dance - 1.5 * iqr_dance
upper_fence_dance=q3_dance + 1.5 * iqr_dance

print(f"The lower fence of danceability is: {lower_fence_dance: .4f}")
print(f"The upper fence of danceability is: {upper_fence_dance:.4f}")

outliers_dance=df_taylor[(df_taylor['danceability']<lower_fence_dance)|(df_taylor['danceability']>upper_fence_dance)]
df_outliers_dance=pd.DataFrame(outliers_dance)
df_outliers_dance['danceability']

df_outliers_dance

df_small_dance=df_outliers_dance[['name', 'danceability', 'popularity']]
df_small_dance

plt.figure(figsize=(9, 4))

# --- Plot 1: Histogram (Left) ---
plt.subplot(1, 2, 1)
sns.histplot(df_taylor['danceability'], kde=True, color='purple', bins=20)

plt.axvline(mean_dance, color="red", linestyle="--", linewidth=1.5, label="Mean")
plt.axvline(median_dance, color="green", linestyle="-", linewidth=1.5, label="Median")
plt.axvline(mode_dance, color="blue", linestyle=":", linewidth=1.5, label="Mode")

plt.xlabel("danceability", fontsize=9)
plt.ylabel("frequency", fontsize=9)
plt.xticks(fontsize=9)
plt.yticks(fontsize=9)

plt.legend(fontsize=8, loc='upper left')

# --- Plot 2: Boxplot (Right) ---
plt.subplot(1, 2, 2)
sns.boxplot(x='danceability', data=df_taylor, color='lightblue', width=0.4)

plt.xlabel("danceability", fontsize=9)
plt.xticks(fontsize=9)
plt.grid(axis='x', linestyle=':', alpha=0.5)

plt.subplots_adjust(bottom=0.2)

plt.tight_layout()
plt.savefig('Figure_2_Danceability_Univariate', dpi=300, bbox_inches='tight')
plt.show()

"""Univariate analysis - album families

"""

df_taylor['album_families'].describe()

df_clean_label=df_taylor.copy()
def clean_labels(label):
    if label == 'THE TORTURED POETS DEPARTMENT':
        return 'TTPD'
    elif label == 'Taylor Swift (Deluxe Edition)':
        return 'Deluxe'
    elif label == 'Live From Clear Channel':
        return 'Live'
    return label
df_clean_label['album_families'] = df_clean_label['album_families'].apply(clean_labels)

#print(df_clean_label['album_families'].value_counts())

plt.figure(figsize=(7.5, 4))

# Generate the countplot and assign it to 'ax' to add labels
ax = sns.countplot(
    data=df_clean_label,
    y='album_families',
    order=df_clean_label['album_families'].value_counts().index,
    palette='Set2'
)

# Add data labels to the end of EVERY horizontal bar by looping through containers
for container in ax.containers:
    ax.bar_label(container, padding=3, fontsize=8)

plt.xlabel("Count", fontsize=9)
plt.ylabel("Album Family", fontsize=9)
plt.xticks(fontsize=9)
plt.yticks(fontsize=9)
plt.grid(axis='x', linestyle=':', alpha=0.5)

plt.subplots_adjust(bottom=0.15)

plt.tight_layout()
plt.savefig('Figure_3_Album_Families_Univariate', dpi=300, bbox_inches='tight')
plt.show()

"""Multivariate analysis"""

# 1. Correlation Heatmap - detacting multicollineary (loudness-energr[r=0.8], energy - acoustiness[r=-0.68], acustiness - loudness[0.67])
accustic_names=df_taylor[[
        'acousticness', 'danceability', 'energy', 'instrumentalness',
       'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity',
       'duration_ms','release_year','track_number']]
acoustic_heatmap=accustic_names.corr()
#plt.figure(figsize=(12, 10))
#sns.heatmap(acoustic_heatmap, annot=True, cmap='coolwarm',fmt='.2f', linewidths=0.5)
#plt.title('Correlation Heatmap')
#plt.savefig('Corelation Heatmap')
#plt.show()

plt.figure(figsize=(6.5, 4.2))
ax = sns.heatmap(
    acoustic_heatmap,
    annot=True,
    cmap='coolwarm',
    fmt='.2f',
    linewidths=0.3,
    cbar=True,
    cbar_kws={"shrink": 0.8},
    annot_kws={"size": 6.5}
)
cbar = ax.collections[0].colorbar
cbar.ax.tick_params(labelsize=7)
plt.xticks(fontsize=7, rotation=45, ha='right')
plt.yticks(fontsize=7)
plt.tight_layout()
plt.savefig('Figure4.jpg', dpi=300, bbox_inches='tight')
plt.show()

# scatterplot energy and loudness
# Clean, shortened dictionary colors matching df_clean_label exactly
eras_colors_clean = {
    'TTPD': '#4B4643',
    'Midnights': '#182443',
    'evermore': '#A37250',
    'folklore': '#7A7A7A',
    'Lover': '#EA99B8',
    'reputation': '#111111',
    '1989': '#72BCD4',
    'Red': '#B22222',
    'Speak Now': '#800080',
    'Fearless': '#DAA520',
    'Deluxe': '#339966',
    'Live': '#FF9933'
}

#df_taylor.columns

# convert release date from srting to date on df_date
df_date=df_clean_label.copy()
df_date['release_date_D']=pd.to_datetime(df_date['release_date'], errors='coerce')
df_date['release_date_D'].info()

#scatterplot popularity and release date
import matplotlib.dates as mdates

plt.figure(figsize=(7.5, 4.5))
sns.scatterplot(
    data=df_date,
    x='release_date_D',
    y='popularity',
    hue='album_families',
    palette=eras_colors_clean,
    alpha=0.8,
    s=40
)
ax = plt.gca()
ax.xaxis.set_major_locator(mdates.YearLocator(2))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))

plt.xlabel('Release Date', fontsize=9)
plt.ylabel('Popularity', fontsize=9)
plt.xticks(rotation=45, fontsize=8)
plt.yticks(fontsize=9)
plt.grid(True, axis='x', linestyle='--', alpha=0.4)

plt.legend(loc='lower right', ncol=1, title='Album Families', fontsize=7, title_fontsize=8)

plt.tight_layout()
plt.savefig('Figure5.jpg', dpi=300, bbox_inches='tight')
plt.show()

plt.figure(figsize=(8.5, 4.5))

sns.boxplot(
    x='album_families',
    y='popularity',
    data=df_clean_label,
    palette='Set2',
    order=df_clean_label.groupby('album_families')['popularity'].median().sort_values(ascending=False).index,
    width=0.6
)

plt.xlabel("Album Family", fontsize=9)
plt.ylabel("Song Popularity (0 - 100)", fontsize=9)
plt.xticks(rotation=45, ha='right', fontsize=8.5)
plt.yticks(fontsize=9)
plt.grid(axis='y', linestyle=':', alpha=0.5)

plt.tight_layout()
plt.savefig('Figure_6_Popularity_By_Album_Family_Boxplot', dpi=300, bbox_inches='tight')
plt.show()

# detact evermore outliers values
q1_evermore=df_taylor[df_taylor['album_families']=='evermore']['popularity'].quantile(0.25)
q3_evermore=df_taylor[df_taylor['album_families']=='evermore']['popularity'].quantile(0.75)
iqr_evermore= q3_evermore - q1_evermore

lower_fence_evermore=q1_evermore - 1.5 * iqr_evermore
upper_fence_evermore=q3_evermore + 1.5 * iqr_evermore

print(f"The lower fence of popularity for 'evermore' albume famliy is: {lower_fence_evermore: .4f}")
print(f"The upper fence of popularity for 'evermore' albume famliy is: {upper_fence_evermore:.4f}")

df_evermore=df_taylor[df_taylor['album_families']=='evermore']
evermore_outliers=df_evermore['popularity']>upper_fence_evermore
evermore_outliers_df=df_evermore[evermore_outliers]
evermore_data=evermore_outliers_df[['popularity','name']]
print(f"--------- evermore album family Song popularity - above upper fence ---------")
evermore_data

# detact evermoreTTPD outliers value
q1_TTPD=df_clean_label[df_clean_label['album_families']=='TTPD']['popularity'].quantile(0.25)
q3_TTPD=df_clean_label[df_clean_label['album_families']=='TTPD']['popularity'].quantile(0.75)
iqr_TTPD= q3_TTPD - q1_TTPD

lower_fence_TTPD=q1_TTPD - 1.5 * iqr_TTPD
upper_fence_TTPD=q3_TTPD + 1.5 * iqr_TTPD

print(f"The lower fence of popularity for 'TTPD' album famliy is: {lower_fence_TTPD: .4f}")
print(f"The upper fence of popularity for 'TTPD' album famliy is: {upper_fence_TTPD:.4f}")

df_TTPD=df_clean_label[df_clean_label['album_families']=='TTPD']
TTPD_outliers=df_TTPD['popularity']>upper_fence_TTPD
TTPD_outliers_df=df_TTPD[TTPD_outliers]
TTPD_data_up=TTPD_outliers_df[['popularity','name']]
print(f"--------- TTPD album family Song popularity - above upper fence ---------")
TTPD_data_up

df_TTPD=df_clean_label[df_clean_label['album_families']=='TTPD']
TTPD_outliers=df_TTPD['popularity']<lower_fence_TTPD
TTPD_outliers_df=df_TTPD[TTPD_outliers]
TTPD_data_down=TTPD_outliers_df[['popularity','name']]
print(f"--------- TTPD album family Song popularity - lower than lower fence ---------")
TTPD_data_down